apiVersion: v1
kind: Service
metadata:
  name: rest-template
  labels:
    app: rest-template
    app.kubernetes.io/name: rest-template
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: rest-template
    app.kubernetes.io/name: rest-template
