apiVersion: v1
kind: Service
metadata:
  name: ubi-nginx
  labels:
    app: ubi-nginx
    app.kubernetes.io/name: ubi-nginx
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: ubi-nginx
    app.kubernetes.io/name: ubi-nginx
