apiVersion: v1
kind: Service
metadata:
  name: http-server
  labels:
    app: http-server
    app.kubernetes.io/name: http-server
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: http-server
    app.kubernetes.io/name: http-server
