apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
  labels:
    app.kubernetes.io/name: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
      app.kubernetes.io/name: foobar
  template:
    metadata:
      labels:
        app: foobar
        app.kubernetes.io/name: foobar
    spec:
      containers:
      - name: foobar
        image: quay.io/fitraalim/foobar:latest
        ports:
        - containerPort: 5000
      imagePullPolicy: Always
