apiVersion: v1
kind: Service
metadata:
  name: foobar
  labels:
    app: foobar
    app.kubernetes.io/name: foobar
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: foobar
    app.kubernetes.io/name: foobar
